### ISSUE TITLE
Safari push packages

### ISSUE THREAD

**Issue by nathany** [RobotsAndPencils/buford#11]
To support Safari push notifications a new package could be added to Buford to create a .pushpackage which could then be served via HTTP.

https://developer.apple.com/library/mac/documentation/NetworkingInternet/Conceptual/NotificationProgrammingGuideForWebsites/PushNotifications/PushNotifications.html

The main issue right now is that we need PKCS #7 signing which isn't currently provided by x/crypto.

**Comment by nathany** [comment]
@wyattjoh If you find/write a PKCS #7 implementation for signing, can you please drop a note here?

**Comment by mdigger** [comment]
https://github.com/mdigger/pkcs7sign/blob/master/pkcs7.go

**Comment by nathany** [comment]
Thanks @mdigger.

**Comment by mdigger** [comment]
The MIT License (MIT)

**Comment by mdigger** [comment]
https://github.com/mdigger/passbook

**Comment by nathany** [comment]
Thanks @mdigger. Do you mind if I bring that code into buford/pkcs7 with your LICENSE?

It would be nice if we could generalize the code some. The `wwdr` variable seems specific to Apple Safari Push.

**Comment by nathany** [comment]
Related: https://github.com/cloudflare/cfssl/blob/master/crypto/pkcs7/pkcs7.go (but no signing)

**Comment by nathany** [comment]
@mdigger Your library looks _very_ similar to https://github.com/st3fan/gocrypto.
