### ISSUE TITLE
Extract bundle-id from certificate

### ISSUE THREAD

**Issue by macteo** [RobotsAndPencils/buford#22]
I've noticed that you can extract the bundle-id from the certificate and put it into the Headers as Topic (it seems to be required), so you can avoid asking for it.

```
cert, err := certificate.Load(filename, passphrase)
if err != nil {
    log.Fatal(err)
}

commonName := cert.Leaf.Subject.CommonName
bundle := strings.Replace(commonName, "Apple Push Services: ", "", 1)

headers := &push.Headers{
	Topic: bundle,
}
```

**Comment by nathany** [comment]
That's a great tip. Thanks!

What do you think of adding a field to push.Service for the Topic and a NewService constructor function to extract it? I'd probably remove Topic from push.Headers when updating PushBytes.

**Comment by macteo** [comment]
I used buford for a single app and using a single SSL certificate for both production and development and if I don't specify the topic it refuses to work, so I tried to extract it from the certificate itself as in my certificate there's only one. I really don't know how you can create a certificate with more than one bundle-id, but if that's the case, the suggested method can fail. The NewService constructor function to extract the bundle-id seems a good fit as API.

**Comment by nathany** [comment]
I don't quite understand this whole Topic thing. Nor why you needed to specify it whereas I didn't.

The library `certificate.Load` depends on will fail if multiple certificates are present in the .p12 (https://github.com/golang/go/issues/14015), so that's not a concern.

**Comment by macteo** [comment]
Me too.
