### ISSUE TITLE
malformed HTTP status code "client"

### ISSUE THREAD

**Issue by sger** [RobotsAndPencils/buford#26]
Hello, 

Install today 1.6 and i'm getting this message malformed HTTP status code "client"

the problem is here 

resp, err := s.Client.Do(req)

if err != nil {
   return err
}

**Comment by Valrox** [comment]
I confirm. The same behavior appeared today after installing 1.6

**Comment by pzinovkin** [comment]
+1

**Comment by nathany** [comment]
That is odd. I was seeing that exact error when I compiled the code with Go 1.5.x. It's probably trying to send HTTP 1.1 requests to Apple for some reason.

**Comment by nathany** [comment]
I rolled back to go1.6rc2 and sent a push notification without that error. I'll try to figure out why this isn't working and open an issue with Go if appropriate.

**Comment by nathany** [comment]
GODEBUG=http2debug=2 has plenty to output in rc2 but only the post url in Go 1.6. It's the same output as GODEBUG=http2client=0 for rc2. Nothing really new here. For some reason HTTP/2 is happening, maybe a configuration issue in the Transport. Maybe a bug. I'm going to attempt a git bisect. Hang tight.

**Comment by nathany** [comment]
This is the commit: https://go.googlesource.com/go/+/79d9f48c73124eb21db99efa4b97cee044f52700

Sounds like I need to change the configuration.

**Comment by nathany** [comment]
Have a look at #27. It does require an API change because the HTTP/2 upgrade [may fail](https://godoc.org/golang.org/x/net/http2#ConfigureTransport).

**Comment by nathany** [comment]
It looks like HTTP/2 clients were accidently disabled in Go 1.6 but the fix will be coming in Go 1.6.1. https://github.com/golang/go/issues/14391

I think it will still be necessary to pull in x/net/http2 because we are specifying a custom cert from Apple.

**Comment by pzinovkin** [comment]
Nice. Thanks.
