### ISSUE TITLE
Error.Timestamp is error

### ISSUE THREAD

**Issue by bjdgyc** [RobotsAndPencils/buford#37]
I find a bug in
https://github.com/RobotsAndPencils/buford/blob/master/push/service.go#L208
the `response.Timestamp` is  Millisecond
but `time.Unix()` require seconds
so the `Error.Timestamp` is error

I fix it by `Timestamp:   time.Unix(response.Timestamp/1000, 0)`

**Comment by nathany** [comment]
Thanks for reporting this issue. If you send a pull request, I'll be sure to merge the change.

**Comment by nathany** [comment]
thanks for your pull request #38. it's merged now.
