### ISSUE TITLE
Accessing push.Service concurrently?

### ISSUE THREAD

**Issue by collinhundley** [RobotsAndPencils/buford#40]
The docs aren't entirely clear about the lifespan of a `push.Service`.  Is a new `Service` supposed to be created for each individual push notification (or batch of notifications), or is it intended to be long-lived and reused?  If the latter is true, is it safe to use across different threads?

Here's what I've got working right now:
    
    package main

    import "github.com/RobotsAndPencils/buford/push"
    ...

    var service push.Service

    // InitAPNS initializes the APNS service for global access.
    func InitAPNS() {
        filename := "/path/to/certificate.p12"
        password := "certificate_password"
        cert, key, err := certificate.Load(filename, password)
        if err != nil {
            log.Fatal(err.Error())
        }
        client, err := push.NewClient(certificate.TLS(cert, key))
        if err != nil {
            log.Fatal(err.Error())
        }
        service = push.Service{
            Client: client,
            Host: push.Development}
    }

    func SendPushNotification(deviceTokens []string, notificationDetails...) {
        ...
        service.PushBytes(token, nil, bytes)
        ...
    }

I initialize my global `Service` once from `main()`, and then reuse it each time I call `SendPushNotification()` - usually from different threads.  After 48 hours of running and maybe 50 total notifications, everything seems to be working ok.  But, I haven't been able to test it under a real load yet.

Am I going about this the right way?  Supposing that `Service` is meant to be long-lived, how can we catch connection errors?  And if it's instead meant to created and destroyed with each notification, what suggestions do you have to avoid reading the certificate from disk each time?  Thanks for the help.

**Comment by nathany** [comment]
Service is meant to be long lived. It should be safe to use across different goroutines. If there is an error, `service.PushBytes` will return the error.

Service is just a wrapper around an HTTP/2 Client using the Go standard library. The standard library provides a connection pool that will reuse a connection for multiple requests, but can also create new connections if there is an error. The standard library takes care of all the hard parts, so the service code is actually very simple.

**Comment by collinhundley** [comment]
Ok, that's the impression that I had while digging through the code but I wanted to be sure. If you have any suggested improvements to the code I've shown, please let me know. Thanks!

**Comment by nathany** [comment]
I think your code is fine. There should probably be some concurrent tests and documentation in Buford to address this concern.

**Comment by nathany** [comment]
@collinhundley I've written a concurrent example #54. Right now I'm considering changing Push to do things concurrently for you.

**Comment by nathany** [comment]
#54 documents concurrent use.
