### ISSUE TITLE
Return status code / response.reason?

### ISSUE THREAD

**Issue by froodian** [RobotsAndPencils/buford#42]
It would be nice in the case of errors to return the status code and reason from Apple as part of your Error struct so that calling code wouldn't have to check for your error strings explicitly in order to respond to various conditions.

**Comment by nathany** [comment]
Hi,

The error responses are all exported so you can compare to them with an if or switch statement. Eg.

```go
id, err := service.Push(deviceToken, &push.Headers{}, p)

if err == push.ErrMissingDeviceToken {
    // handle error
}
```

Is that what you're looking for? I should probably add an example to the documentation.

**Comment by froodian** [comment]
That helps some yeah, but it's still a little suboptimal for me because I'm writing a REST endpoint on top of buford and I'd love to return the literal status code / reason from Apple because some of the calling code is aware of those already (and apple is unlikely to change them any time soon). I could make my REST endpoint check against the exported errors and convert back to Apple's format, but that's obviously a little ugly. The calling code for my REST endpoint isn't in go so it can't reference those errors directly either.

**Comment by nathany** [comment]
So you would like to see the HTTP status code and the textual Reason that Apple provides in a custom error structure?

It changes the API (which is fine) in a way that's a little uglier to work with if someone just wants to check for a match. See https://github.com/RobotsAndPencils/buford/blob/master/push/service_test.go#L100

Willing to consider it though. Especially since we're already doing it sometimes, so it may be better to always return a struct similar to: https://github.com/RobotsAndPencils/buford/blob/master/push/service.go#L96

**Comment by froodian** [comment]
Yeah exactly, I was imagining adding those fields to push.Error, so you could check `e.Err` against `push.ErrMissingDeviceToken` or any of the other exported errors, or `e.Status` or `e.Reason` (or whatever names, or they could be a nested structure, like `e.AppleResponse.Status`/`e.AppleResponse.Reason`, or what have you) against the list of known values that Apple returns, and yeah having it always return a `push.Error` (or `resp.Header.Get("apns-id"), nil` like it does today in the case of success)

**Comment by nathany** [comment]
Instead of:

```go
ErrPayloadEmpty    = errors.New("the message payload was empty")
```

we could also go with:

```go
ErrPayloadEmpty    = errors.New("PayloadEmpty")
```
and skip the mapping of Apple errors to subjectively nicer error messages. 

Then Reason and Err are really the same thing, so we only need one, whichever it's called.

`e.Status` for HTTP Status sounds good to me.

**Comment by froodian** [comment]
yeah that makes sense / sounds good to me. Thanks!

**Comment by nordicdyno** [comment]
I would like to see the way to get raw response from APNS somewhere in API

**Comment by nathany** [comment]
@nordicdyno Do you need the raw timestamp as well (only provided for certain responses)? I'd prefer it to be a `time.Time` rather than Apple's not-quite-a-Unix-time format.

**Comment by nathany** [comment]
@froodian Apologies for the delay in working on this.

I've started on #46. Still thinking about handling for errors that aren't Apple responses (returning the error interface vs. the Error struct). Planning to wrap up the PR today.

**Comment by nathany** [comment]
Ready for review.
