### ISSUE TITLE
Many ESTABLISHED state to APNS, defer close not work?

### ISSUE THREAD

**Issue by bezigon** [RobotsAndPencils/buford#45]
By invoking a `netstat -antup | grep server | awk '{print $5}' | cut -d: -f1 | sort | uniq -c` command on server I got a lot occurencies of APNS IPs with ESTABLISHED state, what is going wrong?

     38 17.110.226.29
     43 17.110.227.88
     36 17.110.227.89
     33 17.110.227.90
     32 17.110.227.91
     37 17.110.227.92
     45 17.110.227.93
     45 17.110.227.94
     48 17.110.227.95
     49 17.110.227.96
     26 17.143.164.136
     19 17.143.164.137
     30 17.143.164.138
     45 17.143.164.139
     39 17.143.164.140
     26 17.143.164.141
     38 17.143.164.142
     49 17.143.164.77
     17 17.143.164.78
     46 17.143.164.79
     15 17.172.233.39
     13 17.172.234.15
      4 17.172.234.16
     15 17.172.234.17
     15 17.172.234.18
     16 17.172.234.19
     10 17.172.234.20
     12 17.172.234.21
     18 17.172.234.22
     13 17.172.234.23

Where first column is occurency of second column (APNS IP).

**Comment by bezigon** [comment]
Something related with https://github.com/RobotsAndPencils/buford/issues/40? In my implementation I use cron-like goroutines and separate Buford instances.

**Comment by nathany** [comment]
Go's HTTP/2 lib opens a connection and keeps it open so that we can send multiple push notifications to Apple on the same connection. 

If you're running multiple processes, you should have one connection per process.

**Comment by nathany** [comment]
@bezigon If you believe there is an issue with Buford, please provide more details, such as a code sample of how you're using it. Thanks.

**Comment by nathany** [comment]
Closing this for now. Feel free to reopen it if you have more details.
