### ISSUE TITLE
queue.Responses undefined (type *push.Queue has no field or method Responses, but does have push.responses)

### ISSUE THREAD

**Issue by wjames2000** [RobotsAndPencils/buford#60]
Demo concurrent run print 
queue.Responses undefined (type *push.Queue has no field or method Responses, but does have push.responses)

**Comment by nathany** [comment]
I made an API change in v0.8.0. https://github.com/RobotsAndPencils/buford/releases/tag/v0.8.0

Please update Buford.

```
go get -u github.com/RobotsAndPencils/buford
```
