### ISSUE TITLE
Return type should be Error

### ISSUE THREAD

**Issue by vnodecg** [RobotsAndPencils/buford#79]
in [#97](https://github.com/RobotsAndPencils/buford/blob/master/push/service.go#L97) return type should be `Error` not builtin `error`. 

With return type `Error` user will have options like getting timestamp of unregistered error

**Comment by nathany** [comment]
Right now some errors that could occur don't conform to the Error type. Such as an error building a request https://github.com/RobotsAndPencils/buford/blob/master/push/service.go#L70 or making an HTTP request: https://github.com/RobotsAndPencils/buford/blob/master/push/service.go#L77

You can use a type assertion to get the `push.Error` type back:
https://github.com/RobotsAndPencils/buford#error-responses

**Comment by vnodecg** [comment]
I was trying to access the timestamp. All I get is `error`

**Comment by nathany** [comment]
Take a look at [type assertions](https://tour.golang.org/methods/15). 

```go
if e, ok := err.(*push.Error); ok {
    log.Println(e.Timestamp)
}
```
