### ISSUE TITLE
remote error: tls: unknown certificate

### ISSUE THREAD

**Issue by azr** [RobotsAndPencils/buford#80]
Hello there,

Recently I started seeing weird errors for push notifications on a DEV server.
No notification is sent now.

```
Post https://api.development.push.apple.com/3/device/{TOKEN}: remote error: tls: unknown certificate
```

Do you know what it could mean ?
Could it be that my certificate is expired ?

1. What version of Go are you using (`go version`)?
1.7
2. What operating system (GOOS) are you using (`go env`) and what version?
linux amd 64

cheers !

**Comment by nathany** [comment]
Hi Adrien,

Hm. "unknown certificate" isn't an error returned by Apple as JSON, it's an error from the crypto/tls package: https://github.com/golang/go/blob/master/src/crypto/tls/alert.go#L55

> An unspecified issue took place while processing the certificate that made it unacceptable.

That's not too helpful. Maybe try recreating the certificate from scratch? 

https://developer.apple.com/library/mac/documentation/IDEs/Conceptual/AppDistributionGuide/AddingCapabilities/AddingCapabilities.html#//apple_ref/doc/uid/TP40012582-CH26-SW11

**Comment by azr** [comment]
Hey Nathan, okay thanks sorry I bothered you !
I'll try this right away :)

**Comment by nathany** [comment]
I appreciate reporting the issue as it may help to improve the documentation here.

Any success with addressing that error?

**Comment by azr** [comment]
Okay, so after recreating my certificates, it was fixed !

I think apple removes outdated certificates automatically, which made us got this error.

We need to be careful with that !

**Comment by nathany** [comment]
Glad you got it to work.

Maybe the README could be improved with what-to-do for some common errors. I created a separate issue for that, #85.

**Comment by azr** [comment]
Good idea, that will surely save someone from a lot of pain and stress haha :)
