### ISSUE TITLE
unexpected bad device token error

### ISSUE THREAD

**Issue by bfitzsimmons** [RobotsAndPencils/buford#9]
So, I'm currently having trouble getting APNS to recognize what I believe to be valid device tokens. While attempting to resolve this issue I looked at the request being sent and was surprised to see HTTP/1.1 as the protocol. Am I incorrect in believing that I should be seeing HTTP/2.0?

```
&{Method:POST URL:https://api.development.push.apple.com/3/device/BBFD8AF1C6A685F8FE4294732D2700B587956508318C770328BE167149F180F6 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Content-Type:[application/json]] Body:{Reader:0xc820573ad0} ContentLength:40 TransferEncoding:[] Close:false Host:api.development.push.apple.com Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr: RequestURI: TLS:<nil> Cancel:<nil>}
```

**Comment by bfitzsimmons** [comment]
Also, should I be using `api.development.push.apple.com` or `api.sandbox.push.apple.com` as the push domain? The docs say `development`, but Buford's code has `sandbox`.

**Comment by nathany** [comment]
It should be HTTP/2, so long as you are using Go 1.6+. Otherwise it won't work.

However, the test suite is still using HTTP/1.1 for the httptest.NewServer.

**Comment by nathany** [comment]
api.sandbox.push.apple.com was and is working, but I've switched it to development in #5.

**Comment by bfitzsimmons** [comment]
I'm pretty sure I'm using 1.6:

```bash
$ go version
go version go1.6beta1 darwin/amd64
```

**Comment by bfitzsimmons** [comment]
I'll attempt printing the version from within the app.

**Comment by bfitzsimmons** [comment]
It's definitely using 1.6:

```bash
go1.6beta1
```

**Comment by bfitzsimmons** [comment]
So, the app is using 1.6, but the protocol is still 1.1. Is anyone else seeing the same thing?

**Comment by nathany** [comment]
What is the specific error you're seeing for device tokens? 
Btw, If you delete and reinstall an app on your device, it will have new device tokens.

I also see HTTP 1.1 if I log the request before sending it. But if I compile with Go 1.5 I get a `malformed HTTP status code "client"` error whereas it works for me with Go 1.6.

Before starting on this project I did a test against https://http2.golang.org/reqinfo to make the Client uses HTTP/2.

**Comment by nathany** [comment]
If you log the response, it does say HTTP/2.0:

`&{200 OK 200 HTTP/2.0...`

**Comment by nathany** [comment]
Btw, v0.2.0 is tagged. It uses development instead of sandbox.

**Comment by bfitzsimmons** [comment]
The error message I'm seeing related to the device token is a simple `bad device token`. It could very well be an issue related to the cert and how the tokens are being generated in the device, but I haven't yet found the solution.

**Comment by nathany** [comment]
Is the certificate signed for a development environment and the device token also for a development environment? I think there is a slightly different error if there is a production/development mismatch, but I haven't tested that case to be sure. 

Of course it could be something else.

**Comment by bfitzsimmons** [comment]
Not surprisingly, it was a problem with the cert. and the device token. Nothing to see here.

Thanks for the help.
