### ISSUE TITLE
APNS Cert fails validation on Go 1.10

### ISSUE THREAD

**Issue by kmcrawford** [RobotsAndPencils/buford#93]
In Go 1.10 returns: `certificate specifies an incompatible key usage: asn1.ObjectIdentifier{1, 3, 6, 1, 5, 5, 7, 3, 1}` for APNS cert. 

This is keeping us from upgrading our systems to use Go 1.10.

1. What version of Go are you using (`go version`)?
`go version go1.10 darwin/amd64`
2. What operating system (GOOS) are you using (`go env`) and what version?
OSX, Apline
3. What did you do? (steps to reproduce or a code sample is helpful)
Attempt to do push notification using a valid cert.
4. What did you expect to see?
The push to go through.
5. What did you see instead?
An error.

A proposed fix is in: https://github.com/RobotsAndPencils/buford/pull/92

**Comment by kmcrawford** [comment]
Any comments on this?  I hate to fork this repo to fix this issue.

**Comment by nathany** [comment]
thanks for the fix.
